### PR TITLE
[Migrate] React to Next.js (TypeScript) with Tailwind CSS 

### PR DESCRIPTION
**Pull request by danmolloy**
This is a pull request for [Issue #51](https://github.com/abhijeetnishal/Password-Shield/issues/51).

I have created an additional dir in the project which is a client built with NextJS, TypeScript and TailwindCSS.

I've completed the following tasks:
- [X] Update the project structure to conform to Next.js conventions.
- [x] Migrate React components to Next.js (with TypeScript) pages and components.
- [x]  Implement the Next.js App Router to handle routing.
- [x]  Replace the current CSS implementation with Tailwind CSS.
- [ ]  Test the application thoroughly to ensure it functions as expected.

The application has been manually tested and there is some test coverage with Jest and React Testing Library. However, some work needs to be done to make this a thorough coverage. I have written many test statements and hope that another contributor can finish this work.

I have utilised a number of NextJS 14 features such as the App Router, layout.tsx, not-found.tsx and loading.tsx. The use of server components is currently limited as useState() and useEffect() are used at a high level.

I kept changes to the styling to a minimum and tried to stay faithful to the current design. I believe all the components are now responsive designed.

In general, I also kept changes to the code to a minimum. Some changes were made as errors arose when migrating to TypeScript.

### CODE REVIEW

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, i think there is an issue with the files/folder as I am not able to see in files in GitHub. Could you check once?

**Comment by abhijeetnishal** [comment]
Hey I am not able to view the files, it's looking like this:
Screenshot_2024-05-22-17-06-20-75_40deb401b9ffe8e1df2f1cc5ba480b12


Even on your repo I am not able to view. Reference:
Screenshot_2024-05-22-17-05-56-86_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, As you see the nextjs-client folder looks different than other folders. I guess either it's not pushed or committed or something else.

**Comment by abhijeetnishal** [comment]
Hey @danmolloy, if you need any help let me know. If you facing any issue. 

Try to check the .git folder sometimes if you pushing from different folder it will create issues.

**Comment by danmolloy** [comment]
Apologies @abhijeetnishal , there was a .git in the nextjs-client dir which was causing issues and creating an empty submodule. I've opened a new pull request which should work now. Dan

**Comment by abhijeetnishal** [comment]
> Apologies @abhijeetnishal , there was a .git in the nextjs-client dir which was causing issues and creating an empty submodule. I've opened a new pull request which should work now. Dan

No problem Dan, it happens. I got the same issue once that's why i thought May be that's the reason.

**Pull request closed without merging**
