### PR TITLE
Adding connection pooling to the server

### PR DESCRIPTION
**Pull request by Abhinavhaldiya**
I have done changes in the dbConnect.ts file by creating a pool which has max connection limit of 20 and idleTimeout of 30 sec and then used that pool to query from database.

Please provide a valuable feedback.(as I am new to Open source)

Thankyou

### CODE REVIEW

**Comment by Abhinavhaldiya** [comment]
> @Abhinavhaldiya is attempting to deploy a commit to the **Abhijeet's projects** Team on [Vercel](https://vercel.com).

Sir, this was by mistake.Sorry for that

**Comment by abhijeetnishal** [comment]
> > @Abhinavhaldiya is attempting to deploy a commit to the **Abhijeet's projects** Team on [Vercel](https://vercel.com).
> 
> Sir, this was by mistake.Sorry for that

No problem @Abhinavhaldiya it's happen.

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, there is an issue when i am trying to login. 
The error message:
Error: Connection terminated due to connection timeout

Look into this issue

**Comment by Abhinavhaldiya** [comment]
> Hey @Abhinavhaldiya, there is an issue when i am trying to login. The error message: Error: Connection terminated due to connection timeout
> 
> Look into this issue

Okay sir I'll try to solve it

**Comment by Abhinavhaldiya** [comment]
Sir i have tried to run the database on my local server Error: self-signed certificate in certificate chain occurs ,but i have tried  it by installing a npm package postgres-pool (npm i postgres-pool) and i hope this will solve the connection timeout problem.

npm package:https://www.npmjs.com/package/postgres-pool

**Comment by abhijeetnishal** [comment]
> Sir i have tried to run the database on my local server Error: self-signed certificate in certificate chain occurs ,but i have tried it by installing a npm package postgres-pool (npm i postgres-pool) and i hope this will solve the connection timeout problem.
> 
> npm package:https://www.npmjs.com/package/postgres-pool

Ok i will check.
Hey @Abhinavhaldiya, don't call me sir just the name

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, I have checked the code and it looks good to me.
Could you pull the code from master branch (git pull origin master) and run the build command (npm run build) and push the code in this PR, then i will merge this.

**Comment by Abhinavhaldiya** [comment]
> Hey @Abhinavhaldiya, I have checked the code and it looks good to me. Could you pull the code from master branch (git pull origin master) and run the build command (npm run build) and push the code in this PR, then i will merge this.

okay @abhijeetnishal i will do it

**Comment by Abhinavhaldiya** [comment]
Done @abhijeetnishal I hope it will be fine

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, Good job. I have this to master branch.
Congrats you are now open source contributer.

**Comment by Abhinavhaldiya** [comment]
Hiii @abhijeetnishal this issue was not under the gssoc as i am not able to make it to the leaderboard.

**Comment by abhijeetnishal** [comment]
Hey @Abhinavhaldiya, I have added required levels it will be visible.

**Comment by Abhinavhaldiya** [comment]
> Hey @Abhinavhaldiya, I have added required levels it will be visible.

Okay thanks sir

**Pull request merged**
