### PR TITLE
feat: Implement reset password

### PR DESCRIPTION
**Pull request by nishant0708**
feat:Implement reset password #45
- Created forgot and reset password pages.
- added backend logic

https://github.com/abhijeetnishal/Password-Shield/assets/101548649/1b2c021b-fe60-485e-abb8-76abda1a8967

### CODE REVIEW

**Comment by nishant0708** [comment]
hey @abhijeetnishal if there are any changes let me know

**Comment by abhijeetnishal** [comment]
> hey @abhijeetnishal if there are any changes let me know

Ok @nishant0708, I will let you know

**Comment by abhijeetnishal** [comment]
Hey @nishant0708, i guess we discussed about pulling the code from ` ui-fix` branch as we have redesigned the UI. I am changing the branch now from master so that you can see the changes too.

**Comment by abhijeetnishal** [comment]
Once done let me know i will review the code. If you need any help let me know.

**Pull request closed without merging**
