### PR TITLE
[feature] Server side search feature

### LINKED ISSUE #3: [feature] Server side search feature
- Implement search functionality (server side)
- Search query should based on website name
- Request URL should looks like: api/get?query=am&limit=10&...
- Response should return an list according to searched result.

### PR DESCRIPTION
**Pull request by HARISH-1222**
Hi @abhijeetnishal 👋

closes #3 

I have done search functionality in the same passwords/all routes and added limit, offset in query.

i.e. query params:  search, limit, offset (which is optional).

End point :

*  password/all/:id (normal get all password)
*  password/all/:id/?query=&offset=0&limit=10 (for search with offset and limit)

### CODE REVIEW

**Comment by abhijeetnishal** [comment]
Hey @HARISH-1222, there is some conflicts arising. Pull the latest code and check.

client/.gitignore -> accept incoming which is project changes.

**Comment by HARISH-1222** [comment]
Hi @Abhinavhaldiya 👋

I made these changes last week and at that time it worked fine

but now when I pull the updated code there are a lot of changes like there is no file encryptDecrypt in middleware
and I was confused

**Comment by abhijeetnishal** [comment]
> Hi @Abhinavhaldiya 👋
> 
> I made these changes last week and at that time it worked fine
> 
> but now when I pull the updated code there are a lot of changes like there is no file encryptDecrypt in middleware and I was confused

Yes, i updated the codebase as the earlier code was little messy that's why. 
Just accept incoming if you haven't added that code else accept current where the conflicts are coming.

**Comment by HARISH-1222** [comment]
Yes but I only have one conflict this is passwordController.ts is deleted

so I only accept the current change to have that passwordController.ts
and once I work on it there is no encryptDecrypt file in middleware folder

**Comment by abhijeetnishal** [comment]
Hey, just do the changes to the latest code, I think it's only a single file code change. So conflict issue is also get resolved.

**Comment by abhijeetnishal** [comment]
Hey @HARISH-1222, did you getting difficulty in fixing changes?

**Comment by HARISH-1222** [comment]
> So conflict issue also get resolved

Yes I will make a PR in 5 mins

**Comment by HARISH-1222** [comment]
I resolved the conflict 
and make all the changes that you mention earlier 
the only problem in the code is I can't get this middleware decrypt, encrypt

**Comment by Abhinavhaldiya** [comment]
Hey @abhijeetnishal @HARISH-1222 sorry for being offline for few days, i was engaged in few important tasks and now I am free for the contribute.If there is anything that i can help.Please reach me out.

Thanks

**Comment by abhijeetnishal** [comment]
> > So conflict issue also get resolved
> 
> import { decrypt, encrypt } from "../middlewares/encryptDecrypt";
> 
> In password controller.ts I am using this decrypt, encrypt
> 
> now where should I get it? now there is no such middleware encryptDecrypt

Hey @HARISH-1222, We are doing only encryption from server side and decrypt is now moved to client side. You will find the encrypt method in utils now. 

If you are facing much issues with the conflicts then you can create a new PR with the latest code 
and add the search logic as it's only single file  change.

Let me know what you are thinking on resolving the conflicts.

**Comment by abhijeetnishal** [comment]
> Hey @abhijeetnishal @HARISH-1222 sorry for being offline for few days, i was engaged in few important tasks and now I am free for the contribution tasks.If there is anything that i can help.Please reach me out.
> 
> Thanks

Hey @Abhinavhaldiya, I guess @HARISH-1222 has already completed this we are solving the conflicts issue.

**Comment by Abhinavhaldiya** [comment]
> > Hey @abhijeetnishal @HARISH-1222 sorry for being offline for few days, i was engaged in few important tasks and now I am free for the contribution tasks.If there is anything that i can help.Please reach me out.
> > Thanks
> 
> Hey @Abhinavhaldiya, I guess @HARISH-1222 has already completed this we are solving the conflicts issue.

Okay ,I will try to see another issue.

**Pull request closed without merging**
